# r for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
latex: false
fortran: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      before_install: |-
        git clone --depth 1 https://github.com/apache/arrow.git
        pushd arrow/cpp
        mkdir build
        pushd build
        cmake ..
        sudo make install
        ldd /usr/local/lib/libarrow.so.10
        popd
        popd
    - os: osx
      osx_image: xcode9.3
      brew_packages: apache-arrow
    #- os: osx
      #osx_image: xcode7.3
      #disable_homebrew: true

addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev
